-- This file must be run once in order to create the database structure

CREATE TABLE "Wifi" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`BSS`	TEXT,
	`NodeId`	INTEGER,
	`Min`	REAL,
	`Max`	REAL,
	`Avg`	REAL
);

CREATE TABLE "Node" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`BuildingId`	INTEGER,
	`X`	REAL,
	`Y`	REAL
);

CREATE TABLE "Link" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Node1Id`	INTEGER,
	`Node2Id`	INTEGER,
	`Distance`	REAL,
	`BuildingId`	INTEGER
);

CREATE TABLE "Campus" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL
);

CREATE TABLE "Building" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`CampusId`	REAL,
	`Name`	TEXT,
	`PixelPerMeter`	REAL DEFAULT 0.0,
	`ImagePath`	TEXT,
	`XOnParent`	REAL DEFAULT 0.0,
	`YOnParent`	REAL DEFAULT 0.0,
	`BgCoordX`	REAL DEFAULT 0.0,
	`BgCoordY`	REAL DEFAULT 0.0,
	`RelativeAngle`	REAL DEFAULT 0.0
);

CREATE TABLE `AliasesLink` (
	`NodeId`	INTEGER,
	`AliasId`	INTEGER
);

CREATE TABLE "Aliases" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL
);
